### ISSUE TITLE
Prebuilt binaries for Electron 8?

### ISSUE THREAD

**Issue by jacobweber** [robinwassen/forcefocus#7]
Hi! I found this plugin from [this issue](https://github.com/electron/electron/issues/2867). I tried to install it using electron-builder, with this in my package.json:

```
"postinstall": "electron-builder install-app-deps"
```

But it looks like there's not a prebuilt binary for Electron 8. I get this error:

```
  • electron-builder  version=22.3.5
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=forcefocus@1.0.0 platform=darwin arch=x64
  • install prebuilt binary  name=forcefocus version=1.0.0 platform=darwin arch=x64
  • build native dependency from sources  name=forcefocus
                                          version=1.0.0
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /Users/jacobweber/.npm/_prebuilds/bf1c5a-forcefocus-v1.0.0-electron-v76-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/robinwassen/forcefocus/releases/download/v1.0.0/forcefocus-v1.0.0-electron-v76-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/robinwassen/forcefocus/releases/download/v1.0.0/forcefocus-v1.0.0-electron-v76-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.0.2 runtime=electron arch=x64 libc= platform=darwin)
    
  ⨯ cannot execute  cause=exit status 1
                    out=
    > forcefocus@1.0.0 install /Users/jacobweber/myapp/node_modules/forcefocus
    > prebuild-install || node-gyp rebuild
    
      CXX(target) Release/obj.target/forcefocus/src/bindings.o
    
                    errorOut=prebuild-install WARN install No prebuilt binaries found (target=8.0.2 runtime=electron arch=x64 libc= platform=darwin)
    ../src/bindings.cc:40:52: error: no viable conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>'
          isolate->ThrowException(Exception::TypeError(String::NewFromUtf8(isolate, "Expected one argument")));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const v8::Local<v8::String> &' for 1st argument
    class Local {
          ^
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::String> &&' for 1st argument
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:7083:47: note: passing argument to parameter 'message' here
      static Local<Value> TypeError(Local<String> message);
                                                  ^
    ../src/bindings.cc:45:21: error: no viable conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>'
          Local<String> message = String::NewFromUtf8(isolate, "Expected first argument to be a window handle buffer");
                        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const v8::Local<v8::String> &' for 1st argument
    class Local {
          ^
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::String> &&' for 1st argument
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
      V8_INLINE Local(Local<S> that)
                ^
    ../src/bindings.cc:50:85: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        unsigned char* windowHandleBuffer = (unsigned char*)node::Buffer::Data(args[0]->ToObject());
                                                                                        ^
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8.h:2794:3: note: 'ToObject' has been explicitly marked deprecated here
      V8_DEPRECATED("Use maybe version")
      ^
    /Users/jacobweber/.electron-gyp/8.0.2/include/node/v8config.h:397:37: note: expanded from macro 'V8_DEPRECATED'
    #   define V8_DEPRECATED(message) [[deprecated(message)]]
                                        ^
    1 warning and 2 errors generated.
    make: *** [Release/obj.target/forcefocus/src/bindings.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/jacobweber/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    gyp ERR! System Darwin 18.7.0
    gyp ERR! command "/Users/jacobweber/.nvm/versions/node/v10.16.3/bin/node" "/Users/jacobweber/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/jacobweber/myapp/node_modules/forcefocus
    gyp ERR! node -v v10.16.3
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! forcefocus@1.0.0 install: `prebuild-install || node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the forcefocus@1.0.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any chance you could create one? Many thanks. I'm building on Mac OS 10.14.6.

**Comment by jacobweber** [comment]
Actually I realized that my issue wasn't caused by a focus problem, so I don't need this anymore.

**Comment by joaomlemos** [comment]
@robinwassen  - I'm facing similar issue with Electron 9.  Are you planning to update this ? 

Thanks!
